name: docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - dockerfile/jenkins-base/**
      - .github/workflows/dockerfile.yaml

env:
  GITHUB_TOKEN: ${{ secrets.MISTEOWORKFLOW }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow if no skipped
        if: contains(github.event.head_commit.message, '[skip ci]')
        run: gh workflow run docker --repo MaaAssistantArknights/MaaRelease
